logging:
  level: INFO
  file: logs/app.log

file:
  base_path : assets
  font:
    en:
      roboto:
        regular: fonts/Roboto-Regular.ttf
        bold: fonts/Roboto-Bold.ttf
    cn:
      wenkai:
        regular: fonts/LXGWWenKaiTC-Regular.ttf
        bold: fonts/LXGWWenKaiTC-Bold.ttf
      notosan_tc:
        regular: fonts/NotoSansTC-Regular.ttf
        bold: fonts/NotoSansTC-Bold.ttf
  dict:
    cedict: dict/cedict_ts.u8